//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADMIN_ASPNET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa
    {
        public string CUIT { get; set; }
        public string RazonSocial { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
