//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADMIN_ASPNET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        public int DNI { get; set; }
        public string ApellidoYNombre { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
